language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script:
- bash -ex .travis-opam.sh
env:
  global:
    - PINS="logs-async.dev:https://github.com/vbmithr/logs-async.git async-uri.dev:https://github.com/vbmithr/async-uri.git monocypher.dev:https://github.com/vbmithr/ocaml-monocypher.git fixtypes.dev:. fix.dev:. fix-ftx.dev:. fix-async.dev:. fix-coinbasepro.dev:. fix-deribit.dev:. fixmsg.dev:."
  matrix:
    - OCAML_VERSION="4.08" PACKAGE="fix"
    - OCAML_VERSION="4.09" PACKAGE="fix"
    - OCAML_VERSION="4.08" PACKAGE="fixtypes"
    - OCAML_VERSION="4.09" PACKAGE="fixtypes"
    - OCAML_VERSION="4.08" PACKAGE="fix-async"
    - OCAML_VERSION="4.09" PACKAGE="fix-async"
    - OCAML_VERSION="4.08" PACKAGE="fix-msg"
    - OCAML_VERSION="4.09" PACKAGE="fix-msg"
os:
- linux
