language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script:
- bash -ex .travis-opam.sh
env:
  global:
    - PINS="logs-async.dev async-uri.dev fixtypes.dev:. fix.dev:. fix-async.dev:. fix-ftx.dev:. fix-coinbasepro.dev:. fix-deribit.dev:. fixmsg.dev:."

  matrix:
    - OCAML_VERSION="4.09" PACKAGE="fix"
    - OCAML_VERSION="4.09" PACKAGE="fixtypes"
    - OCAML_VERSION="4.09" PACKAGE="fix-async"
    - OCAML_VERSION="4.09" PACKAGE="fixmsg"
os:
- linux
